
target ?= debug
TARGET_DEFAULT = $(target)

LIBRAIRIES = libmaniganc

libmaniganc_C_SRCS = $(wildcard *.c)
libmaniganc_INCLUDES = include

include ../../mk/makelib.mk
include ../../mk/build_info.mk
include ../../mk/default_targets.mk
